const topTenRecovered = {
  lastUpdated: "2020-11-09T08:00:19.157Z",
  totalDeaths: 1256179,
  totalConfirmed: 50395314,
  totalRecovered: 33032762,
  statistics: [
    {
      name: "India",
      alpha2: "IN",
      alpha3: "IND",
      numeric: "356",
      deaths: 126611,
      confirmed: 8553657,
      recovered: 7917373,
      travel: null,
      foreignImmigration: { status: "ห้ามคนไทยเข้า", note: null },
    },
    {
      name: "Brazil",
      alpha2: "BR",
      alpha3: "BRA",
      numeric: "076",
      deaths: 162397,
      confirmed: 5664115,
      recovered: 5147172,
      travel: "มีความเสี่ยง",
      foreignImmigration: { status: "ห้ามคนไทยเข้า", note: null },
    },
    {
      name: "United States",
      alpha2: "US",
      alpha3: "USA",
      numeric: "840",
      deaths: 237570,
      confirmed: 9968155,
      recovered: 3881491,
      travel: "ห้ามเดินทาง",
      foreignImmigration: { status: "เข้าได้", note: null },
    },
    {
      name: "Russia",
      alpha2: "RU",
      alpha3: "RUS",
      numeric: "643",
      deaths: 30292,
      confirmed: 1760420,
      recovered: 1315928,
      travel: null,
      foreignImmigration: { status: "ห้ามคนไทยเข้า", note: null },
    },
    {
      name: "Argentina",
      alpha2: "AR",
      alpha3: "ARG",
      numeric: "032",
      deaths: 33560,
      confirmed: 1242182,
      recovered: 1062911,
      travel: null,
      foreignImmigration: { status: "ห้ามคนไทยเข้า", note: null },
    },
    {
      name: "Colombia",
      alpha2: "CO",
      alpha3: "COL",
      numeric: "170",
      deaths: 32791,
      confirmed: 1143887,
      recovered: 1038082,
      travel: null,
      foreignImmigration: { status: "ห้ามคนไทยเข้า", note: null },
    },
    {
      name: "Peru",
      alpha2: "PE",
      alpha3: "PER",
      numeric: "604",
      deaths: 34821,
      confirmed: 920010,
      recovered: 846215,
      travel: null,
      foreignImmigration: { status: "ห้ามคนไทยเข้า", note: null },
    },
    {
      name: "Mexico",
      alpha2: "MX",
      alpha3: "MEX",
      numeric: "484",
      deaths: 95027,
      confirmed: 967825,
      recovered: 824355,
      travel: null,
      foreignImmigration: { status: "เข้าได้", note: null },
    },
    {
      name: "South Africa",
      alpha2: "ZA",
      alpha3: "ZAF",
      numeric: "710",
      deaths: 19809,
      confirmed: 737278,
      recovered: 679688,
      travel: null,
      foreignImmigration: {
        status: "เข้าได้ แต่ต้องมีเอกสารใบรับรองแพทย์",
        note: null,
      },
    },
    {
      name: "Iran",
      alpha2: "IR",
      alpha3: "IRN",
      numeric: "364",
      deaths: 38291,
      confirmed: 682486,
      recovered: 520329,
      travel: "ห้ามเดินทาง",
      foreignImmigration: { status: "เข้าได้", note: null },
    },
  ],
};

  module.exports = topTenRecovered;